### Тест с несколькими нарушениями
POST http://127.0.0.1:5000/api/analyze/code
Content-Type: application/json

{
    "code": "Процедура Тест2()\n    // правильная строка\n    Счетчик = 0;\n\n    // две строки с нарушениями\n    А = 1; Б = 2;\n    В = 3; Г = 4; Д = 5;\n\n    // в цикле\n    Для i = 1 По 10 Цикл\n        Элемент = i; Сообщить(Элемент);\n    КонецЦикла;\nКонецПроцедуры",
    "module_name": "test2.bsl"
}
